version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: sveta908
      POSTGRES_DB: my_db
    ports:
      - "5438:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    container_name: my_postgres
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/my_db
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: sveta908
    depends_on:
      - postgres

volumes:
  postgres-data: